IMPORTING ORIGINAL FOLDERS

In [17]:

import os
import pandas as pd

# Define the root directory where your folders are located
root_directory = 'C:/Users/Rachel/OneDrive - UCLA IT Services/Documents/DWP_Electrification_Cal/data/data/'

# Create an empty dictionary to store the DataFrames
df_dict = {}

# Iterate over each folder
folders = os.listdir(root_directory)
for folder_name in folders:
    folder_path = os.path.join(root_directory, folder_name)
    
    # Check if the path is a directory
    if os.path.isdir(folder_path):
    
        # Get a list of files in the folder
        files = os.listdir(folder_path)
        
        # Iterate over each file in the folder
        for file_name in files:
            file_path = os.path.join(folder_path, file_name)
            
            # Check if the path is a file
            if os.path.isfile(file_path):
            
                # Read the file as a DataFrame and store it in the dictionary
                key = os.path.join(folder_name, file_name)
                df = pd.read_csv(file_path)
        
                
                # Select specific columns
                selected_columns = ['upgrade', 'in.geometry_building_type_recs', 'timestamp',
                                   'units_represented','out.site_energy.total.energy_consumption.kwh',
                                   'out.electricity.total.energy_consumption.kwh','out.fuel_oil.total.energy_consumption.kwh',
                                   'out.natural_gas.total.energy_consumption.kwh','out.propane.total.energy_consumption.kwh',
                                    'out.load.cooling.energy_delivered.kbtu','out.load.heating.energy_delivered.kbtu',
                                   'out.load.hot_water.energy_delivered.kbtu','out.emissions.all_fuels.lrmer_95decarbby2035_15_2025start.co2e_kg',
                                   'out.emissions.all_fuels.lrmer_lowrecost_15_2025start.co2e_kg','out.emissions.all_fuels.lrmer_lowrecost_25_2025start.co2e_kg',
                                   'out.emissions.all_fuels.lrmer_midcase_15_2025start.co2e_kg']
                df = df[selected_columns]
               
                # Accounting for units represented to get load of single unit
                df['elec.consumed'] = df['out.electricity.total.energy_consumption.kwh'] / df['units_represented']
                df['nat_gas.consumed'] = df['out.natural_gas.total.energy_consumption.kwh'] / df['units_represented']
                df['total.consumed'] = df['out.site_energy.total.energy_consumption.kwh'] / df['units_represented']
                df['elec.load'] = df['elec.consumed'] / .25
                df['nat_gas.load'] = df['nat_gas.consumed'] / .25
                df['total_load'] = df['total.consumed'] / .25
                df['elec_sum'] = sum(df['elec.consumed']) 
                df['nat_gas_sum'] = sum(df['nat_gas.consumed']) 
                df['total_sum'] = sum(df['total.consumed']) 
                df_dict[key] = df

In [18]:
df_dict['baseline\\up00-3b-mobile_home.csv']

,upgrade,in.geometry_building_type_recs,timestamp,units_represented,out.site_energy.total.energy_consumption.kwh,out.electricity.total.energy_consumption.kwh,out.fuel_oil.total.energy_consumption.kwh,out.natural_gas.total.energy_consumption.kwh,out.propane.total.energy_consumption.kwh,out.load.cooling.energy_delivered.kbtu,...,out.emissions.all_fuels.lrmer_midcase_15_2025start.co2e_kg,elec.consumed,nat_gas.consumed,total.consumed,elec.load,nat_gas.load,total_load,elec_sum,nat_gas_sum,total_sum
0,0,Mobile Home,2018-01-01 00:15:00,592494.588144,481988.041965,174572.101818,1211.243465,265965.548179,40232.953583,5350.611119,...,123252.634389,0.294639,0.448891,0.813489,1.178557,1.795564,3.253957,7875.519332,5468.415281,14118.874738
1,0,Mobile Home,2018-01-01 00:30:00,592494.588144,489644.939986,176269.198086,1108.916845,270473.809270,41783.890203,4059.810690,...,125263.357726,0.297503,0.456500,0.826413,1.190014,1.826000,3.305650,7875.519332,5468.415281,14118.874738
2,0,Mobile Home,2018-01-01 00:45:00,592494.588144,499437.427209,177731.185141,1116.013004,278282.068373,42307.231966,4018.164156,...,127780.189653,0.299971,0.469679,0.842940,1.199884,1.878715,3.371760,7875.519332,5468.415281,14118.874738
3,0,Mobile Home,2018-01-01 01:00:00,592494.588144,510024.826218,179396.804378,969.122503,286162.353496,43487.961944,3806.541651,...,130370.209283,0.302782,0.482979,0.860809,1.211129,1.931915,3.443237,7875.519332,5468.415281,14118.874738
4,0,Mobile Home,2018-01-01 01:15:00,592494.588144,551699.222680,206794.896992,1048.315643,295202.151081,48660.494526,4238.503378,...,145539.403421,0.349024,0.498236,0.931146,1.396096,1.992944,3.724586,7875.519332,5468.415281,14118.874738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,0,Mobile Home,2018-12-31 23:00:00,592494.588144,453155.494385,186412.066209,1307.964119,232422.569925,33011.121100,9096.620017,...,116196.548236,0.314622,0.392278,0.764826,1.258490,1.569112,3.059306,7875.519332,5468.415281,14118.874738
35036,0,Mobile Home,2018-12-31 23:15:00,592494.588144,450906.153748,177841.839014,1115.587235,236635.914627,35312.334664,8385.239102,...,115190.873555,0.300158,0.399389,0.761030,1.200631,1.597557,3.044120,7875.519332,5468.415281,14118.874738
35037,0,Mobile Home,2018-12-31 23:30:00,592494.588144,454309.684728,180812.302278,1051.154106,236796.500716,35648.479739,6031.241396,...,116094.896208,0.305171,0.399660,0.766774,1.220685,1.598641,3.067098,7875.519332,5468.415281,14118.874738
35038,0,Mobile Home,2018-12-31 23:45:00,592494.588144,472099.543704,184248.383480,1088.763752,249618.551313,37147.685356,5664.170781,...,120634.390959,0.310971,0.421301,0.796800,1.243882,1.685204,3.187199,7875.519332,5468.415281,14118.874738
35039,0,Mobile Home,2019-01-01 00:00:00,592494.588144,483965.528732,184524.897096,1508.359663,259242.717632,38689.893700,5282.814436,...,123437.699178,0.311437,0.437544,0.816827,1.245749,1.750178,3.267308,7875.519332,5468.415281,14118.874738

In [19]:
import numpy as np
keys = list(df_dict.keys())
sums = [[''] * 4 for _ in range(55)]

In [20]:
count = 0
for x in keys:
    df = df_dict[x]
    sums[count][0] = x
    sums[count][1] = df['elec_sum'][0]
    sums[count][2] = df['nat_gas_sum'][0]
    sums[count][3] = df['total_sum'][0]
    count = count+1

In [6]:
from itertools import product

names = [row[0] for row in sums]
elec_sums = [row[1] for row in sums]
nat_gas_sums = [row[2] for row in sums]
total_sums = [row[3] for row in sums]
names = list(product(names, repeat=2))
elec_combos = list(product(elec_sums, repeat=2))
nat_gas_combos = list(product(nat_gas_sums, repeat=2))
total_combos = list(product(total_sums, repeat=2))

In [7]:
both_names = [row[0] + '\\' + row[1] for row in names]
elec_multipliers = [row[1] / row[0] for row in elec_combos]
nat_gas_multipliers = [row[1] / row[0] for row in nat_gas_combos]
total_multipliers = [row[1] / row[0] for row in total_combos]

In [8]:
##all_multipliers = np.array([both_names, elec_multipliers, nat_gas_multipliers, total_multipliers]).T

In [8]:
split_columns = [row.split('\\') for row in both_names]
column1, column2,column3,column4 = zip(*split_columns)
combined_array = np.array([column1, column2, column3, column4, elec_multipliers,nat_gas_multipliers, total_multipliers]).T
headers = ['starting_upgrade','starting_home','other_upgrade','other_home','elec_mult','nat_gas_mult','total_mult']
mult_df = pd.DataFrame(combined_array, columns=headers)
mult_df['starting_home_cut'] = mult_df['starting_home'].str[8:]
mult_df['other_home'] = mult_df['other_home'].str[8:]
filtered_df = mult_df[mult_df['starting_home_cut'] == mult_df['other_home']]

In [9]:
# Concatenate columns 1 and 2
concat = filtered_df['starting_upgrade'] +"\\" + filtered_df['starting_home'] + "\\" + filtered_df['other_upgrade']
new_array = np.column_stack((concat, filtered_df['elec_mult'], filtered_df['nat_gas_mult'], filtered_df['total_mult']))
headers = ['name','elec_mult','nat_gas_mult','total_mult']
mult_df = pd.DataFrame(new_array, columns=headers)

In [10]:
print(mult_df)

                                                  name           elec_mult  \
0            baseline\up00-3b-mobile_home.csv\baseline                 1.0
1     baseline\up00-3b-mobile_home.csv\basic_enclosure  0.9010702014429808
2    baseline\up00-3b-mobile_home.csv\enhanced_encl...  0.9010702014429808
3    baseline\up00-3b-mobile_home.csv\heat_pumps_hi...   0.933783602866858
4    baseline\up00-3b-mobile_home.csv\heat_pumps_mi...   1.159895054100884
..                                                 ...                 ...
600  whole_home_electrification_min_efficiency\up07...  0.8279533856699208
601  whole_home_electrification_min_efficiency\up07...  0.7585479886335345
602  whole_home_electrification_min_efficiency\up07...  0.6943880126713551
603  whole_home_electrification_min_efficiency\up07...  0.6901840765447821
604  whole_home_electrification_min_efficiency\up07...                 1.0

           nat_gas_mult          total_mult
0                   1.0                 1.0
1    0.8039921586851044  0.8569768294373951
2    0.8039921586851044  0.8569768294373951
3    0.5339223951870814  0.7487019833850941
4    0.5338895220528267  0.8748135326730514
..                  ...                 ...
600  12.287983392407005  1.2106765333096168
601                 1.0  0.7662354196965105
602                 1.0  0.7041183518620574
603                 1.0  0.7000482830213116
604                 1.0                 1.0

[605 rows x 4 columns]

In [11]:
mult_df.to_csv('Multipliers.csv', index=False)

In [ ]:
Zone =